import Link from "next/link";
import { Building2 } from "lucide-react";

export default function Footer() {
  return (
    <footer className="mt-24 border-t border-forest-900/10 bg-mint-100/60">
      <div className="mx-auto max-w-6xl px-4 py-10">
        <div className="flex flex-col items-center justify-between gap-6 md:flex-row">
          <div className="flex items-center gap-2">
            <span className="flex h-7 w-7 items-center justify-center rounded-full bg-forest-900 text-emerald-400">
              <Building2 size={14} strokeWidth={2.5} />
            </span>
            <span className="font-display text-sm font-bold text-forest-900">
              EstatePredict
            </span>
          </div>
          <p className="text-center text-xs text-ink-500">
            Estimates are generated by a statistical model trained on historical
            sales data and are not an appraisal. &copy; {new Date().getFullYear()} EstatePredict.
          </p>
          <div className="flex gap-5 text-xs font-medium text-ink-700">
            <Link href="/" className="hover:text-forest-900">Home</Link>
            <Link href="/login" className="hover:text-forest-900">Log in</Link>
            <Link href="/signup" className="hover:text-forest-900">Sign up</Link>
          </div>
        </div>
      </div>
    </footer>
  );
}
